project:
  type: manuscript
  resources:
    - /resources
    - /resources/*.pdf

manuscript:
  article: index.qmd

bibliography: references.bib
csl: the-lancet.csl

format:
  # elsevier-pdf:
  #   journal:
  #     name: "The Lancet Digital Health"
  #     formatting: preprint
  #     model: 1p
  #     layout: onecolumn
  #     cite-style: super
  #   include-in-header: 
  #     text: |
  #       \newpageafter{author}
  docx:
    reference-doc: _extensions/frpQuarto/custom-reference-doc.docx
    toc: false
    number-sections: true
    tbl-cap-location: top
    citeproc: false
    title-block: true
    filters:
      - _extensions/frpQuarto/wordcount.lua
      - _extensions/frpQuarto/summary_wordcount.lua
      - authors-block
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/citeproc.lua
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/wordcount.lua
  html:
    theme: [default, _extensions/frpQuarto/styles.scss]
    html-table-processing: none
    tbl-cap-location: top
    toc: true
    toc-depth: 3
    template: _extensions/frpQuarto/template.html

    include-after-body:
        text: |
              <script>
              document.addEventListener("DOMContentLoaded", () => {

                /* --------------------------------------------------
                * 1. FIGCAPTION TRANSFORMATION
                * -------------------------------------------------- */
                document.querySelectorAll("figcaption").forEach(e => {
                  e.innerHTML = e.innerHTML.replace(
                    /((.*?)\.)\s*(.*)/,
                    '<div class="figcaption-title-lancet">$1</div>' +
                    '<details class="dropdown-card">' +
                      '<summary>' +
                        '<span class="figcaption-dropdown">Show full caption</span>' +
                        '<span class="arrow">' +
                          '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">' +
                            '<polyline points="6 9 12 15 18 9"/>' +
                          '</svg>' +
                        '</span>' +
                      '</summary>' +
                      '<div class="figcaption-subtext">$3</div>' +
                    '</details>'
                  );
                });

                /* --------------------------------------------------
                * 2. WORDCOUNT → TOC SIDEBAR
                * -------------------------------------------------- */
                const source = document.querySelector(".wordcount-source");
                const toc = document.querySelector("nav#TOC, nav[id$='TOC']");

                if (source && toc) {
                  const container = document.createElement("div");
                  container.classList.add(
                    "add-info",
                    "content-visible",
                    "no-count"
                  );

                  container.innerHTML = source.innerHTML;

                  const tocContent = toc.querySelector(".toc-content") || toc;
                  tocContent.after(container);
                }

              });
              </script>

    crossref:
      title-delim: " "

    template-partials:
      - _extensions/frpQuarto/title-block.html
      - _extensions/frpQuarto/toc.html

    shortcodes: 
      - _extensions/frpQuarto/summary.lua
      - _extensions/frpQuarto/acknowledgements.lua
      - _extensions/frpQuarto/contributors.lua
      - _extensions/frpQuarto/datasharing_statement.lua
      - _extensions/frpQuarto/declaration_of_interests.lua
      - _extensions/frpQuarto/panel.lua

    filters:
      - _extensions/frpQuarto/wordcount.lua
      - _extensions/frpQuarto/summary_wordcount.lua

    other-links:
      - text: Supplementary material
        icon: file-earmark-pdf
        href: '#'
      - text: Statistical analysis plan
        icon: file-earmark-pdf
        href: 'resources/files_for_submission/myTabu_SAP_signed.pdf'
      - text: Zipped files
        icon: file-earmark-pdf
        href: '#'

    code-links:
      - text: Disclosure form
        icon: file-earmark-word
        href: 'resources/coi_disclosure.docx'
      - text: Author statement form
        icon: file-earmark-pdf
        href: 'resources/tldh-author-signatures.pdf'
