project:
  type: manuscript
  resources:
    - /resources
    - /resources/*.pdf

manuscript:
  article: index.qmd

bibliography: references.bib
csl: the-lancet.csl

format:
  html:

    theme: [default, _extensions/frpQuarto/styles.scss]

    html-table-processing: none
    tbl-cap-location: bottom

    other-links:
      - text: Manuscript
        icon: file-earmark-word
        href: '#'
      - text: Supplementary material
        icon: file-earmark-pdf
        href: '#'
      - text: Trial registry
        icon: file-earmark-pdf
        href: resources/GermanClinicalTrialsRegister.pdf
      - text: Study protocol
        icon: file-earmark-pdf
        href: resources/myTabu_frontiers_study_protocol.pdf
      - text: Statistical analysis plan
        icon: file-earmark-pdf
        href: resources/myTabu_SAP_signed.pdf

    code-links:
      - text: Disclosure form
        icon: file-earmark-word
        href: 'resources/coi_disclosure.docx'
      - text: Author statement form
        icon: file-earmark-pdf
        href: 'resources/tldh-author-signatures.pdf'

    toc: true
    toc-depth: 3
