---
title: "Effectiveness of a web-based intervention for individuals who committed sexual offenses against children: a concealed, prospective, parallel group, placebo-controlled, randomized trial in Germany."

shorttitle: "Effectiveness of a web-based intervention for individuals who committed sexual offenses against children."

version: "0.9.0"

date: last-modified
date-format: long

lightbox: true
notebook-links: false

authors:
  - name: Peter Fromberger
    initials: "PF"  # variables not defined by quarto become metadata.variable
    degrees: PhD
    is_prof: false
    affiliations:
      - ref: UMG
    orcid: 0000-0002-4818-8730
    email: peter.fromberger@med.uni-goettingen.de
    roles: [writing – original draft, visualization, conceptualization, funding acquisition, project administration, supervision, software, methodology]
    corresponding: true
  - name: Sonja Schröder
    degrees: PhD
    is_prof: false
    initials: "SSch"
    affiliations:
      - ref: Mor
    orcid: 0000-0002-4140-1818
    roles: [writing – review & editing, investigation, methodology, resources, project administration]
    corresponding: false
  - name: Bruno Siegel
    degrees: MSc
    is_prof: false
    initials: "BS"
    affiliations:
      - ref: UMG
    roles: [writing – review & editing, investigation, resources, supervision]
    corresponding: false
  - name: Safiye Tozdan
    degrees: PhD
    is_prof: false
    initials: "ST"
    affiliations:
      - ref: UKE
    orcid: 0000-0001-6645-3617
    roles: [writing – review & editing, investigation, conceptualization, resources]
    corresponding: false
  - name: Andreas Leha
    degrees: PhD
    is_prof: false
    initials: "AL"
    affiliations:
      - ref: UMGmath
    roles: [formal analysis, visualization, writing – review & editing]
  - name: Fabian Kück
    degrees: PhD
    is_prof: false
    initials: "FK"
    affiliations:
      - ref: UMGmath
    roles: [formal analysis, visualization, writing – review & editing]
    orcid: 0000-0002-8634-9101
    corresponding: false
  - name: Louisa Neumann
    degrees: MSc
    is_prof: false
    initials: "LM"
    affiliations:
      - ref: Wun
    roles: [writing – review & editing, investigation, methodology, resources]
    orcid: 0000-0003-1959-5035
    corresponding: false
  - name: Sabine Horn
    degrees: MSc
    is_prof: false
    initials: "SH"
    affiliations:
      - ref: UzK
    roles: [writing – review & editing, conceptualization]
  - name: Claudia Buntrock
    degrees: PhD
    is_prof: true
    initials: "CB"
    affiliations:
      - ref: Mag
    roles: [writing – review & editing, conceptualization, funding acquisition, resources]
    corresponding: false
    orcid: 0000-0002-4974-5455
  - name: Kirsten Jordan
    degrees: PhD
    is_prof: false
    initials: "KJ"
    affiliations:
      - ref: UMG
    orcid: 0000-0001-8083-5857
    roles: [writing – review & editing, project administration]
    corresponding: false
  - name: Sonja Etzler
    degrees: PhD
    is_prof: false
    initials: "SE"
    affiliations:
      - ref: KrimZ
    roles: [writing – review & editing, conceptualization, funding acquisition]
    orcid: 0000-0002-3993-3591
    corresponding: false
  - name: Martin Rettenberger
    degrees: PhD
    is_prof: true
    initials: "MR"
    affiliations:
      - ref: KrimZ
    roles: [writing – review & editing, conceptualization, funding acquisition]
    corresponding: false
    orcid: 0000-0002-0979-4295
  - name: Anja Schiemann
    degrees: PhD
    is_prof: true
    initials: "AS"
    affiliations:
      - ref: UzK
    roles: [writing – review & editing, conceptualization, funding acquisition]
    corresponding: false
  - name: Peer Briken
    degrees: MD
    is_prof: true
    initials: "PB"
    affiliations:
      - ref: UKE
    orcid: 0000-0002-1360-014X
    roles: [writing – review & editing, conceptualization, funding acquisition]
    corresponding: false
  - name: Jürgen Leo Müller
    degrees: MD
    is_prof: true
    initials: "JLM"
    affiliations:
      - ref: UMG
    roles: [writing – review & editing, conceptualization, funding acquisition]
    corresponding: false
    orcid: 

affiliations:
  - id: UMG
    name: Clinic for Psychiatry and Psychotherapy – Forensic Psychiatry, University Medical Center Göttingen
    city: Göttingen
    country: Germany
  - id: UMGmath
    name: Scientific Core Facility for Medical Biometry and Statistical Bioinformatics, University Medical Center Göttingen
    city: Göttingen
    country: Germany
  - id: UKE
    name: Institute for Sex Research, Sexual Medicine & Forensic Psychiatry, Center for Psychosocial Medicine, University Medical Center Hamburg-Eppendorf
    city: Hamburg
    country: Germany
  - id: KrimZ
    name: Centre for Criminology
    city: Wiesbaden
    country: Germany
  - id: UzK
    name: Criminal Law, Criminal Procedure, and Criminal Policy, University of Cologne
    city: Cologne
    country: Germany
  - id: Mor
    name: Massregelvollzugszentrum Niedersachsen
    city: Moringen
    country: Germany
  - id: Wun
    name: Clinic for Forensic Psychiatry and Psychotherapy, KRH Psychiatry Wunstorf
    city: Wunstorf
    country: Germany
  - id: Mag
    name: Institute of Social Medicine and Health Systems Research (ISMHSR), Otto-von-Guericke-University Magdeburg
    city: Magdeburg
    country: Germany

summary:
  background: |
    Child Sexual Abuse (CSA) and Child Sexual Exploitation Material (CSEM) offenses impose severe harm on survivors and society. While tertiary prevention for convicted offenders is well-researched in-person, evidence for secondary prevention — targeting individuals at risk but not yet convicted — is limited, with few high-quality studies. CSEM-specific programs remain particularly under-evaluated, suffering from small samples, short follow-ups, and reliance on self-reported outcomes. A growing number of CSEM offenders and limited access to outpatient treatment have created a post-release care gap. Web-based interventions (WBIs) may improve accessibility, yet empirical evidence for indivudals who have committed CSA or CSEM offenses remains scarce. Only one study evaluated a guided WBI (Prevent It), showing a small effect on CSEM viewing, but with low conviction rates in the sample. To date, no WBI has been rigorously tested for ICCO with formal convictions. This study evaluates \@myTabu, a new guided WBI for ICCO, in a randomized controlled trial, testing its effectiveness in reducing dynamic risk factors compared to a psychological placebo.
  methods: |
    This prospective, parallel-group, placebo-controlled RCT was conducted online in Germany with 1:1 randomization. Eligible participants were individuals under community supervision for CSA (§176ff StGB) or CSEM (§184b StGB), aged ≥18, with ≥6 months probation and online access. Exclusions included severe psychiatric or cognitive impairments. Randomization was stratified by offense type, supervision type, and static risk, using a block design (block size 4). Participants, outcome assessors, and analysts were blinded. The intervention, \@myTabu, comprised six guided cognitive-behavioral modules targeting dynamic risk factors; the placebo arm delivered non-specific psychoeducation on healthy living. Primary outcome was the CARES (Child Sexual Abuse Risk Evaluation Self-Report). Secondary outcomes included module-specific questionnaires on meaningful risk factors. Analysis followed intention-to-treat principles. Primary analysis used MMRM with treatment group, time (six assessments), treatment-by-time interaction, baseline CARES, and stratification factors as fixed effects, unstructured covariance, and multiple reference-based imputation for sensitivity. Secondary outcomes were analyzed using non-parametric Brunner-Munzel tests with Bonferroni-Holm correction. All tests were two-sided at α = 0.05. The trial was prospectively registered on April 24, 2020 in the [German Clinical Trial Register (DRKS00021256)](https://drks.de/search/en/trial/DRKS00021256).
  findings: |
    Of 385 screened individuals, 369 were randomized (182 placebo, 187 intervention); 213 included in ITT analysis. The MMRM for the primary outcome (CARES) showed no significant treatment effect over time (all p≥0·15). Within-arm analyses revealed significant reductions in self-reported risk factors at module one (intervention: p = 0·005) and module three (p<0·01) in bot trial arms. Secondary outcomes showed a significant decrease in self-reported child sexual interest (ESIQ, p=0·001) and improved treatment readiness (CVTRQ, p=0·006) in the intervention arm. There were no significant differences in re-offense rates as reported by community supervisor or adverse events. The intervention arm required longer to complete modules, with higher working time in modules one, four, and five (all p ≤ 0·046). As a side effect, therapeutic alliance (WAI-SR) improved significantly in the intervention arm (p ≤ 0·006). No serious safety concerns were reported.
  interpretations: |
    This RCT found no significant superiority of the WBI \@myTabu over placebo in reducing dynamic risk factors among ICCO, despite a small reduction in sexual interest in children. Unexpectedly, emotion regulation worsened in the intervention arm, while social support increased only in the placebo group. Robust improvements in therapeutic alliance with supervision officers suggest potential benefits. The null result aligns with recent meta-analyses showing smaller effects in high-quality studies. Differences in sample characteristics and treatment intensity may explain the lack of efficacy. High dropout, prolonged module completion, and low baseline risk may have attenuated detectable effects. While the CARES is a promising new measure, its link to official recidivism remains unverified. The study represents the largest RCT to date on WBIs for ICCO, but routine implementation is not justified without re-working the WBI. Future research should focus on blended models, a higher RNR-based personalization, and direct comparison with in-person treatment programs.
  funding: |
    The work was funded by the German Federal Ministry of Education and Research (BMBF, Funding number: 01KR1807A). The funder of the study had no role in study design, data collection, data analysis, data interpretation, or writing of the report.
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: r-init

library(here)

# run SAP analysis script from MBSB (Dr. Fabian Kück und Dr. Andreas Leha)
source(here::here("_scripts/Fromberger_SAP.R"))

# run analysis for secondary endpoints from MBSB
source(here::here("_scripts/analysis_secondary_endpoints.R"))

# run sensitivity analysis for main endpoint
#source(here::here("_resources/MBSB/rbmi.R"))

# run script to remove outlier
#source(here::here("_resources/MBSB/remove_outlier.R"))

# # load functions to create diffscores and their tbls
source(here::here("_scripts/prim_diffscore_functions.R"))
source(here::here("_scripts/sec_diffscore_functions.R"))

# # load functions to create pairwise tbls
source(here::here("_scripts/prim_pairwise_functions.R"))
source(here::here("_scripts/sec_pairwise_functions.R"))
```

<!-- Metric for docx -->

::: {.no-count .content-visible when-format="docx"}
**Manuscript metrics:**

-   *Summary*: {{< meta summary-wordcount >}} (max. 300 words)
-   *Manuscript*: {{< words-body >}} (max. 4500 words)
-   *Citations*: max. 30

{{< pagebreak >}}
:::

<!-- SUMMARY -->
{{< summary >}}

::: {.no-count .content-visible when-format="docx"}
## Summary {.abstract .unnumbered}

### Background {.unnumbered}
Child Sexual Abuse (CSA) and Child Sexual Exploitation Material (CSEM) offenses impose severe harm on survivors and society. While tertiary prevention for convicted offenders is well-researched in-person, evidence for secondary prevention — targeting individuals at risk but not yet convicted — is limited, with few high-quality studies. CSEM-specific programs remain particularly under-evaluated, suffering from small samples, short follow-ups, and reliance on self-reported outcomes. A growing number of CSEM offenders and limited access to outpatient treatment have created a post-release care gap. Web-based interventions (WBIs) may improve accessibility, yet empirical evidence for indivudals who have committed CSA or CSEM offenses remains scarce. Only one study evaluated a guided WBI (Prevent It), showing a small effect on CSEM viewing, but with low conviction rates in the sample. To date, no WBI has been rigorously tested for ICCO with formal convictions. This study evaluates \@myTabu, a new guided WBI for ICCO, in a randomized controlled trial, testing its effectiveness in reducing dynamic risk factors compared to a psychological placebo.

### Methods {.unnumbered}
This prospective, parallel-group, placebo-controlled RCT was conducted online in Germany with 1:1 randomization. Eligible participants were individuals under community supervision for CSA (§176ff StGB) or CSEM (§184b StGB), aged ≥18, with ≥6 months probation and online access. Exclusions included severe psychiatric or cognitive impairments. Randomization was stratified by offense type, supervision type, and static risk, using a block design (block size 4). Participants, outcome assessors, and analysts were blinded. The intervention, \@myTabu, comprised six guided cognitive-behavioral modules targeting dynamic risk factors; the placebo arm delivered non-specific psychoeducation on healthy living. Primary outcome was the CARES (Child Sexual Abuse Risk Evaluation Self-Report). Secondary outcomes included module-specific questionnaires on meaningful risk factors. Analysis followed intention-to-treat principles. Primary analysis used MMRM with treatment group, time (six assessments), treatment-by-time interaction, baseline CARES, and stratification factors as fixed effects, unstructured covariance, and multiple reference-based imputation for sensitivity. Secondary outcomes were analyzed using non-parametric Brunner-Munzel tests with Bonferroni-Holm correction. All tests were two-sided at α = 0.05. 

### Findings {.unnumbered}
Of 385 screened individuals, 369 were randomized (182 placebo, 187 intervention); 213 included in ITT analysis. The MMRM for the primary outcome (CARES) showed no significant treatment effect over time (all p≥0·15). Within-arm analyses revealed significant reductions in self-reported risk factors at module one (intervention: p = 0·005) and module three (p<0·01) in both trial arms. Only one secondary outcome reached signifance after correction for multiple comparisons: self-reported child sexual interest decreased (ESIQ, p=0·001) in the intervention arm. There were no significant differences in re-offense rates as reported by community supervisor or adverse events. The intervention arm required longer to complete modules, with higher working time in modules one, four, and five (all p ≤ 0·046). As a side effect, therapeutic alliance (WAI-SR) improved significantly in the intervention arm (p ≤ 0·006). No serious safety concerns were reported.

### Interpretations {.unnumbered}
This RCT found no significant superiority of the WBI \@myTabu over placebo in reducing dynamic risk factors among ICCO, despite a unexpected small reduction in sexual interest in children. Robust improvements in therapeutic alliance with supervision officers suggest potential benefits. The null result aligns with recent meta-analyses showing smaller effects in high-quality studies. Differences in sample characteristics and treatment intensity may explain the lack of efficacy. High dropout, prolonged module completion, and low baseline risk may have attenuated detectable effects. While the CARES is a promising new measure, its link to official recidivism remains unverified. The study represents the largest RCT to date on WBIs for ICCO, but implementation is not justified without re-working the WBI. The results suggest future work needs to focus on improving engagement and adherence to digital interventions.

### Funding {.unnumbered}
The work was funded by the German Federal Ministry of Education and Research (BMBF, Funding number: 01KR1807A). The funder of the study had no role in study design, data collection, data analysis, data interpretation, or writing of the report.
:::

{{< pagebreak >}}

<!-- PANEL -->

::: {.research-panel .no-count custom-style="research-panel"}
## Research in context {.unnumbered custom-style="research-panel-title"}

### Evidence before this study {.unnumbered custom-style="research-panel-subtitle"}

Before undertaking this study, no published data on the efficacy of web-based interventions (WBI) in reducing risk-factors for recidivism of Individuals who committed CSA or CSEM Offences (ICCO) was available. The results have been published online 2021. The results of a placebo-controlled RCT of an WBI exclusively for CSEM users in the dark field have been reported for the first time in 2022 (Prevent It). The RCT demonstrated a small, but significant reduction of time spended on viewing CSEM based on self-reports (Cohen’s d 0·18). The RCT involved 160 individuals with CSEM use but only 6.9% had prior convictions, limiting generalizability to ICCO. In 2024, an updated review revealed no further empirical evidence. A systematic search was conducted in PubMed, PsycINFO, Scopus, and Web of Science from January 2024 to March 2025 using the terms ("web-based intervention" OR "digital intervention") AND ("child sexual abuse" OR "child sexual exploitation material" OR "CSEM") AND ("recidivism" OR "re-offense") AND ("randomized controlled trial"). Results indicate, to the best of our knowledge, that no data on effectiveness WBIs for ICCO is published yet. 

### Added value of this study {.unnumbered custom-style="research-panel-subtitle"}
This study is the first randomized controlled trial to evaluate a WBI specifically designed for individuals who have committed child sexual abuse (CSA) or child sexual exploitation material (CSEM) offences (ICCOs). It addresses a critical gap in the literature by assessing the effectiveness of a WBI in reducing dynamic risk factors among a population with criminal convictions, which has not been previously evaluated. Unlike prior studies focusing on secondary prevention with minimal conviction history, this trial targets ICCO with a structured, modular WBI delivered in a controlled trial setting. The study provides the first empirical evidence on the impact of a WBI on dynamic risk factors in this high-risk group, offering a foundation for scalable, accessible post-release care solutions.

### Implications of all the available evidence {.unnumbered custom-style="research-panel-subtitle"}

Authors should state the implications for practice or policy and future research of their study combined with existing evidence.
:::

{{< pagebreak >}}

<!-- INTRODUCTION SECTION -->

{{< include _includes/txt_introduction.qmd >}}

<!-- METHODS SECTION -->

{{< include _includes/txt_method.qmd >}}

<!-- RESULTS SECTION -->

{{< include _includes/txt_results.qmd >}}

<!-- DISCUSSION SECTION -->

{{< include _includes/txt_discussion.qmd >}}

{{< pagebreak >}}

:::: no-count
<!-- CONTRIBUTORS -->

<!-- Is automatically filled with metadata defined above; do not delete the shortcode -->

{{< contributors >}}

<!-- DATA SHARING -->

## Data sharing {.unnumbered}

The source code, the content of the WBI, and the de-identified data will be made available on reasonable request from the corresponding author (peter.fromberger\@med.uni-goettingen.de). Requests, which can be submitted via email to the corresponding author, must include a detailed description of the research question and aims. Data sharing will be authorized following proposal approval and the execution of a signed data access agreement, strictly for scientific use. Code and content sharing follows the same procedure, strictly for non-commercial use.

<!-- DECLARATION OF INTEREST -->

<!-- Is automatically filled with metadata defined above; do not delete the shortcode -->

{{< declaration_of_interests >}}

<!-- ACKNOWLEDGEMENTS -->

## Acknowledgments {.unnumbered}

The work was funded by the German Federal Ministry of Education and Research (BMBF, Funding number: 01KR1807A). The funder had no role in study design, data collection, data analysis, data interpretation, or writing of the report. A local LLM (Qwen 3) was used for language and grammar correction. The authors are grateful to all participants and SOs for their time, trust and motivation.

{{< pagebreak >}}

## References {.unnumbered}

::: {#refs}
:::
::::