## Introduction

Child sexual abuse (CSA), hands-on as well as hands-off offenses like the use of Child Sexual Abuse Material (CSAM), constitutes one of the most severe adverse experiences in child development [@worldhealthorganizationRespondingChildrenAdolescents2017]. Recently, a meta-analysis found lifetime prevalence rates of 11.4% for sexual harassment and 8.7% for any form of hands-on sexual violence [@piolantiGlobalPrevalenceSexual2025]. Beyond its profound short- and long-term consequences for survivors, CSA represents a substantial challenge for society due to high economical costs [@kewleyPreventingChildSexual2023]. These figures clearly demonstrate the importance of preventing CSA or the use of CSAM.

### Effectiveness of prevention programs

In CSA prevention, a distinction is commonly drawn between primary, secondary, and tertiary treatment programs. Primary prevention initiatives are directed at children and their parents, whereas secondary prevention programs seek to engage adults identified as being at risk for sexual child offenses, but have not yet been convicted. Tertiary programs have the longest history and are designed for individuals who committed sexual offenses against children and have been convicted for their offenses [@kewleyPreventingChildSexual2023].
In recent years, secondary treatment approaches have been promoted and in the last few years more and more secondary prevention programs have been implemented worldwide [@setoEvaluatingChildSexual2024]. However, in a recent meta-analysis, @setoEvaluatingChildSexual2024 identified only five publications exploring the effectiveness of secondary prevention programs for adults, none of them a randomized clinical trial. Besides too low sample sizes and the lack of adequate control groups, most of these studies did not provide data on the number of re-offenses based on criminal records [@kewleyPreventingChildSexual2023]. Recently @beierPreventingChildSexual2024 published data on self-reported recidivism rates based on a sample of n = 56 individuals diagnosed with pedophilic or hebephilic disorder (26.8% already known to the justice system and 16.1% had no sexual offenses in their history before treatment) who finished the secondary prevention program. In a 1-11 years follow up, 7.7% of participants of the prevention program with a history of CSA had re-offended, whereas 89.1% of previous exclusive CSAM users reported recidivism. The authors reported no data on adequate control groups nor recidivism rates based on criminal records. Compared to recidivism rates for CSAM-exclusive user of 4.1% based on official records (38.3% based on self-reports; [@baskurtMetaanalysisRecidivismRates2024]), the effectiveness of secondary treatment program  Dunkelfeld project has been questioned [@garringtonConceptualFrameworkInternet2024; see @konigGermanDunkelfeldApproach2025 and  @beierPreventingChildSexual2025 for a discussion]. In summary, currently it is not possible to draw meaningful conclusions on the effectiveness of secondary treatment programs, especially due to a lack of methodological adequate studies [@setoEvaluatingChildSexual2024].
The effectiveness of tertiary treatment programs for individuals who already committed CSA or used CSAM has been studied more extensively. A recent meta-meta-analysis (MMA) and meta-analysis demonstrated that cognitive-behavioral treatment programs based on the Risk-Need-Responsivity model [@andrewsPsychologyCriminalConduct2010] are most effective in reducing re-offenses of individuals who have sexually offended. Across meta-analysis, there is consistent evidence for a small but stable treatment effect [e.g. @holperModeratorsSexualRecidivism2024; @koehlerMetaevaluativeSynthesisEffects2025; @olverSexualOffenseTreatment2025; @schmuckerEffectsSexualOffender2015; @schmuckerSexualOffenderTreatment2017]. In their recent MMA of 21 meta-analyses on tertiary treatment programs, @OlverSexualOffenseTreatment2025 reported a treatment effect with an odds ratio (OR) of 0.67, indicating that participants in tertiary treatment programs exhibited approximately a 33% lower risk of recidivism relative to controls. The meta-analyses identified several moderator variables: community treatment programs provide higher effect-sizes than institutional treatment programs; individual treatment programs show higher effect-sizes than group programs, high-intensity programs are more effective than low-intensity programs, and the higher the design quality of the study, the lower the effect size [@holperModeratorsSexualRecidivism2024; @olverSexualOffenseTreatment2025]. Up to now, most of the mentioned meta-analyses only report on tertiary treatment programs for individuals who have been convicted for CSA. The figure for individuals who have used CSAM is not as well studied. Since the world wide web is more and more accessible and CSAM is more and more in the focus of the law enforcement agencies, the number of individuals convicted for the use of CSAM is arising worldwide [@baskurtMetaanalysisRecidivismRates2024]. A recent review shed light on the methodological weakness of existing studies on the effectiveness of prevention programs for individuals who have used CSAM: mostly, the studies suffer from small sample sizes, to short follow-up periods and self-reports as main outcome. Besides these limitating factors, the meta-analysis demonstrated preliminary support for the effectiveness of these programs [@gouveiaSystematicReviewEffectiveness2025]. To sum up, meta-analyes demonstrate a broad empirical basis for a small but significant effectiveness in reducing recidivism of tertiary prevention programs for individuals sentenced for CSA. For individuals who used CSAM and for secondary prevention programs, the empirical proof of effectiveness is still pending. It has been assumed, that one reason for small effect-sizes with regard to individuals used CSAM is the fact, that most included prevention programs have been initially designed for CSA but not for CSAM-exclusive offenses [@setoEvaluatingChildSexual2024].

### Treatment targets: risk factors for recidivism

To achieve a reduction in re-offenses, it seems to be most promising to target dynamic factors, which are changeable and strong associated with recidivism [@setoEmpiricallybasedDynamicRisk2023]. @mannAssessingRiskSexual2010 introduced the term meaningful psychological risk factors for sexual offending by identifying those risk factors in the literature, which are dynamic and therefore changeable by treatment and are empirically proved in enhancing the risk for recidivism. Recently, @setoEmpiricallybasedDynamicRisk2023 replicated the findings of Mann et al. and proofed the meaningful risk factors with a broader and more recent literature basis. Meaningful risk factors can be sorted into four risk domains, which are defined by concrete dynamic risk variables: (1) Atypical sexuality umfasst sexual preoccupation and paraphilic sexual interests; (2) Self-regulation problems, defined as impulsivity, lifestyle instability and emotion regulation deficits; (3) antisocial cognitions like offense-supportive attitudes and beliefs, hostile masculinity and non-compliance with interventions; and (4) relationship problems, defined as a low capacity for adult intimacy, existing emotional congruence with children, and negative social influences (see also @tbl-sec-outcomes). The emprirical basis for risk factors for CSAM-exclusive offences is not as broad as for sexual offending in the sense of in-person offences. @babchishinChildSexualExploitation2018 elaborated in their review risk factors for CSEM-exclusive offenders. Atypical sexual interests, sexual pre-occupation, sexual arousal, access to the internet and children, and distorted cognitions are assumed to play a key role in recidivism. Thus, there is a overlap between risk factors for CSA offenses and risk factors for CSAM offenses [@reichelReviewRiskFactors2024]. But it is assumed, that e.g. the content of offense-supportive attitudes differs from the content of offense-supportive attitudes for mixed offenders or CSA-exclusive offenders. Access to children or the internet is a so-called facilitating factor in the sense of the Motivation-Facilitation Model of sexual offending and therefore only indirect changeable by treatment [@setoMotivationFacilitationModelSexual2019]. Some of the dynamic risk assessment tools developed for hands-on and mixed offenders seems to be also valid for CSAM-exclusive offenders, also highlighting the overlap of risk factors [@babchishinACUTE2007STABLE2007Predict2023]. On the other side, forementioned small treatment effects for CSAM-exclusive offenders may reflect the fact, that some specific risk variables are not considered in an sufficient amount in current prevention programs.

Two main theoretical frameworks behind treatment programs can be identified: the RNR framework and the GLM framework \[LIT\]. Both frameworks address the same risk factors but with different therapeutical haltungen as well as different techniques (e.g. DBT elements, etc.) and from a practioniar point of view, most programs seems to be eklektik....The same seems to be true for treatment programs for CSA and CSAM: slightly different contents but all treatment programs addressing the same risk factors.....

### Gaps in Post-Release Care

Besides the above mentioned encouraging small but stable treatment effect of tertiary treatment programs, there exists a care gap in the treatment of CSA and CSAM offenders originating from only having few possibilities of community-based treatment and an increase of convicted ISAC and ICCSEM under community supervision within the last years: For example, @schmidtOutpatientTherapistsPerspectives2022 showed that 63% of n = 427 Swiss outpatient therapists working in the primary healthcare system are unwilling to provide treatment for individuals who have a sexual interest in children and have already been convicted. The study further underlines, that the unwillingness to treat those patients is correlated with stigmatizing attitudes and not feeling to be competent enough. In a German sample, @stiels-glennAvailabilityOutpatientPsychotherapy2010 showed that, 87% of included psychotherapists are not willing to provide treatment, whereas only 2.7% would do so. Furthermore, most of the above mentioned secondary prevention programs, do (at least officially) not accept already convicted ISAC and ICCSEM under CS for treatment [@beierGermanDunkelfeldProject2015]. Additionally to this unwillingness of professionals to treat individuals who have abused a child or consumed child abusive material, the number of individuals convicted for the use of child abusive material, rised in the last years resulting in a increased demand for treatment. In consequence, even if the court ordered treatment, many of convicted ISAC and ICCSEM under CS have difficulties to receive professional treatment during community supervision, especially in rural areas. One possible solution to close this gap may be the use of a digital health intervention (DHI) [@hillertWebBasedInitiativesPrevent2024; @wildWebBasedHealthServices2019].

### Webbased interventions

Digital health interventions (DHIs) are assumed to be able to provide a greater accessibility for individuals who face challenges in availing mental health services owing to limited availability or stigma associated with seeking help resulting in reaching a wider population as it is possible with in-face interventions (IFIs). Additionally, DHIs are assumed to be more cost-effective with greater flexibility for clinicians as well as patients compared to IFIs. Meta-analytics demonstrate support for the effectiveness of DHIs compared with active interventions for schizophrenia spectrum disorders, major depressive disorder, social anxiety disorder, and panic disorder. Notable treatment effects compared with a waiting list were also observed for specific phobias, generalized anxiety disorder, obsessive-compulsive disorder, post-traumatic stress disorder, and bulimia nervosa. The data base and number of high-qualitative RCTs differ between the different mental health disorders, the implementation of DHIs is recommended as a tool to bridge the gap in care for individuals on waiting lists [@crocamoDigitalHealthInterventions2025]. Meta-analysis demonstrated that stand-alone web-based interventions with guidance tend to have greater effect sizes than web-based interventions without professional assistance. Webbased interventions with professional assistance showed smaller attrition rates, a higher number of completed modules, and larger symptom reduction in users suffer from, e.g., depression, anxiety disorders, and eating disorders [@baumeisterImpactGuidanceInternetbased2014; @heberBenefitWebandComputerbased2017; @cowpertwaitEffectivenessWebbasedPsychological2013; @lehrOccupationalEMentalHealth2016; @richardsComputerbasedPsychologicalTreatments2012]. Despite the qualitative and quantitative reduction of overall therapeutic contact in web-based interventions (e.g., absence of social and non-verbal signals), studies seem to indicate that a comparable perceived quality of the therapeutic alliance can be achieved as in in-face settings [@anderssonTherapeuticAllianceGuided2012; @ebertWebbasedRehabilitationAftercare2013; @bengtssonTherapistsExperiencesConducting2015]. It is assumed, that DHIs have also the potential to bridge the gap in the care of individuals with regard to tertiary prevention of individuals who have abused a child ore used CSAM [@wildWebBasedHealthServices2019; @hillertWebBasedInitiativesPrevent2024]. To date, studies on the effectiveness of WBIs for individuals who committed CSA or CSEM offenses are scarce [@wildWebBasedHealthServices2019; @hillertWebBasedInitiativesPrevent2024; @schroderWebBasedInterventionsIndividuals2023] . @schroderWebBasedInterventionsIndividuals2023 identified six web-based interventions (WBIs) already implemented in secondary prevention programs, but none implemented in tertiary treatment programs. Furthermore, only for one of these WBIs, a placebo-controlled clinical trial reported on the effectiveness of the WBI. In 2022, @latthEffectsInternetdeliveredCognitive2022 evaluated a guided WBI exclusively for individuals who commit CSEM offenses. The participants were recruited mainly via Darknet forums and could take part anonymously. The results showed that, compared with users of a psychological placebo WBI (n = 78), participants of the WBI Prevent It (n = 76) reported a statistically significant, but small decrease in weekly viewing of CSEM (d = .18 from pre to post; d = .20 from post to follow-up). Besides of some methodological weakness of this clinical trial [@setoEvaluatingChildSexual2024], it provides first preliminary support for the potential effectiveness of WBIs for CSEM [@hillertWebBasedInitiativesPrevent2024]. For tertiary prevention, there exist no proof of effectiveness for WBIs.

### Aim of the study

In consequence, the study aimed to develop and provide a newly developed WBI to bridge the gap in post-release care of individuals, who have been sentenced for CSA or the use of CSAM. By doing so, the current RCT evaluates the effectiveness of the WBI in reducing dynamic risk factors for re-offending compared to a web-based placebo arm and to evaluate the individual effects of treatment modules within the web-based intervention on reducing dynamic risk factors based on self reports. The primary hypothesis constitutes that participants who take part in the web-based intervention show significantly lower values on dynamic risk factors from baseline to inter-, and post-treatment, compared to an web-based placebo intervention. Furthermore, we assumed that, in contrast to the placebo arm, each online module within the intervention arm will reduce the dynamic risk factors targeted in this module in a statistically significant manner.