## Method {#method}

### Patient and public involvement

The project team was advised by a multidisciplinary team, including a police officer, a supervision officer, and a representative of patients during the clincal trial as well as during development of the HBI (meeting once a year).

### Study design

The trial follows a concealed, prospective, parallel group, placebo-control trial with 1:1 randomization at a single site in Germany (Human Medical Centre Göttingen, Göttingen). Due to ethical considerations, both treatment arms have been provided as an add-on to community supervision as Usual (CSaU). CSaU comprises all orders of the court and treatment as usual (e.g., in-face contacts with supervision officers, therapeutic treatment ordered by court, medical treatment) and ensures the necessary maßnahmen ordered by court to prevent society. This potential confounding variable has been reduced by adding additional psycho-therapeutical treatment and medical treatment as stratum. Data on re-offenses based on criminal records will be assessed in a five-year follow up and reported as soon as the data are available. The trial was prospectively registered on April 24, 2020 in the [German Clinical Trial Register (DRKS00021256)](https://drks.de/search/en/trial/DRKS00021256). The study design has been prospectively published [@frombergerMyTabuAPlaceboControlled2021]. The report follows strictly the CONSORT guidelines for randomized trials [@hopewellCONSORT2025Statement2025].

### Participants

All sexual offenders under community supervision (§§56, 57, 68 StGB) from all German states with the exception of Hamburg, Bremen and Saarland, which are sentenced for at least one case of CSA (§§176 StGB) or CSAM (§184b StGB), were eligible for the trial. There exist no exclusion criteria regarding gender. Only persons who are older than 18 years are included. Exclusion criteria are (1) a probation period shorter than 6 months at enrollment, (2) no access to a PC, tablet or smart phone, (3) a severe acute psychiatric disorder (e.g., acute psychosis), (4) a severe cerebro-organic disorder, (5) a severe cognitive impairment, (6) withdrawal of the informed consent. All participants gave written informed consent. The participants were credited with monetary compensation after completing a session, which they could request as a voucher if they had saved €15 (or a multiple thereof). The total amount of compensation was €120 when all sessions were completed (one introductory session and 24 content sessions). However, the participants were told that they would not receive any confirmation of having met the treatment requirements set by the court by taking part in the clinical trial. The clinical trial protocol was approved by the medical ethical board of the University Medical Center Göttingen, Göttingen, Germany, on February 21, 2020 (reference number 16/2/20).

### Randomisation and masking

The clinical trial comprises two parallel groups (intervention group and placebo group). Subjects are randomly allocated to treatment using an allocation ratio of 1:1. The randomization lists are centrally generated using a computerized system (secuTrial®, interActive Systems GmbH, Germany), stratified by the offense type (§176 ff StGB vs. \$184 b StGB), type of community supervision, external treatment in addition to community supervison as usual, and static risk to re-offend at baseline (assessed with the modified Static-99, LIT und genauere Erläuterungen noch ergänzen). At screening, each subject receives the next consecutive screening number. At randomization, each subject eligible for study participation receives the next consecutive randomization number according to his stratum from a block of randomization numbers (block size: 4). Due to security reasons, blinding of supervision officers (SOs) and supporting therapists was not possible. Nevertheless, subjects, outcome adjudicators, members of the data safety monitoring board (DSMB) and data analysts (observer) have been blinded until the end of the data analysis.

### Procedures

For the recruitment of participants, scientific staff informed community supervisors about the clinical trial and asked them to inform eligible individuals under their supervision. For eligible individuals, an individual meeting with an independent research assistant took place at the supervision office. During this meeting, the research assistant provided detailed information about the goals and procedure of the trial, data security and advantages or disadvantages of taking part in the trial. If the potential participant was further interested to take part, he or she received an information letter, the informed consent, an intervention agreement, and a letter releasing the supervision officer from the confidentiality obligation. In the intervention agreement, the participant agreed not to commit offenses during the participation and is informed that any violation could lead to exclusion. Furthermore, the research assistant performs the pre-intervention assessments [WELCHE?]. If a potential participant does not want to take part in the trial, he or she was asked for informed consent in filling out a questionnaire on reasons for not wanting (Questionnaire of Non Participating; QNP) as well as the questionnaires on demographic data. Further, the participant was asked for allowance to assess his or her officially registered re-offenses in a 5-years follow up. After obtaining the written informed consent, the intervention agreement, and the release from confidentiality, the participant was randomly allocated to one of the trial arms. After allocation, the username as well as the initial password necessary to log in was delivered by post to the supervision officer, who gave it to the participant at their next meeting. After the first log-in, the participant had to change the initial password due to security reasons. After changing the initial password, the participant had to go through an introduction, which explains the usage of the intervention website, before he or she can start with the first online module. The starting procedure for the placebo condition was the same as for the experimental condition. Also in both trial arms, the provided content was divided into six online modules. Each module was further divided into four sessions. Participants were advised to use the intervention regularly and work through one session per week. Before the first module and after each consecutive module, the specific pre-post Questionnaires for this module were provided within the app. Before each questionnaire, due to ethical reasons, the participant was informed if the his answers will be viewable by their community supervisor or not (this was the fact for all questionnaire items of the primary endpoint as well as the Mood and Risk  Questionnaire, MRQ). Only if all questionnaires at a specific timepoint have been filled in and all guided tasks are revised by the online coach, the participant was able to start the first session of the next module. After the last session of each module and filling in post questionnaires, the participant has to wait one week in order to ensure a time difference between the post measurement of the last module and the pre measurement of the next module. This was not the fact after the last session of the last module (SEE TABLE XX FOR AN OVERVIEW OF MEASUREMENT TIMEPOINTS). Consequently, the intervention as well as the placebo arm consists of 4 modules, each of which can be completed in 29 weeks (24 weeks plus 5 weeks waiting time). Within each session, the participant was able to work on the lections in a self-paced manner. In cases where a participant completes all sections in under seven days, a mandatory waiting period was applied, requiring seven full days to elapse before commencement of the subsequent session. Furthermore, prior to progressing, all guided tasks must have been reviewed and formally marked as completed by the coach. The clinical trial ends for the individual participant if he has finished the content of the last section in module six and filled-in the post questionnaires at this timepoint. After finishing, the participants can log in one more week e.g. to download the individual digital first aid kit or to request the expense allowance. After this week, the account of the participant was closed and the participant has not further access to the HBI. To prematurely exclude a participant from the clinical trial, the supervision officer had to fill in a questionnaire on exclusion reasons (Exclusion Questionnaire, EQ) and the supervisor had to request the exclusion within the HBI. After receiving the request, the PI closed the access to the HBI for this participant.

Due to pseudonymization and data security aspects, the trial staff (online coaches as well as scientific staff or PIs) had no possibility to contact a participant during the clinical trial directly. All communication with participants takes place within the app, communication with supervisors per Email, telephone or in presence. The supervisors of participants, who did not log in within the last four weeks, have been informed automatically about this fact by email and requested to ask the client about the reasons and to remind him to log-in on a regular basis. Also, six month before the end of the clinical trial, all supervisors have been pleased to inform their clients about the coming end of the clinical trial. Supervisors not logged in within the last month have been automatically reminded by Email.

#### Aufbau und Struktur der HBI

The HBI \@myTabu consists of three isolated sections, one only for participants, one only for the coaches and one section only for supervisors. The access to these sections was secured by username and password to full-fill criteria of the DSGVO. On the landing page of the coach section, a dashboard informs the coach on tasks he has to perform (e.g. unanswered messages by a client, open guided tasks). Each coach had only access to the participants he was responsible for. The landing page links to the in-app messenger and a page for working on guided tasks together with the participant.

The supervisor section, only accessible by participating community supervisors, provides a landing page which summarized important key aspects (treatment progress, critical events) of all participants, which have been supervised by this supervisor. Due to security reasons, the supervisor was able to see the raw values of the primary endpoint [UND NOCH VIEL MEHR]. If a item of the primary endpoint has been graded as a potential hint to recidivism by lawyers within the research team during development of the app, additional judicial information have been provided. Furthermore, each supervisor has to fill in a questionnaire at baseline about demographic and criminological characteristics of the participant as well as every four weeks during the course of the clinical trial of his client in order to assess changes from baseline.

The structure and organization of the content were identical across both trial arms. At the beginning of each session, key elements from the previous session or module were recapped. At the end of each session, the most important points of that session or module were summarized. Content created during exercises was partly dynamic integrated in consecutive sessions. For example, at the start of the intervention participants created a list of positive activities, which was later used to suggest ways in which they could reward themselves for completing a session or module. In both trial arms, the program included digital psycho-educational blocks incorporating multimedia elements such as videos and graphics, as well as guided and unguided exercises. A total of eighteen different online exercises (e.g., fill‑in‑the‑gap tasks, multiple‑choice questions) were integrated into the HBI. These exercises were either offered as self‑guided tasks with automated feedback or as coach‑guided tasks in which feedback was provided by online coaches. In the intervention arm, the most relevant aspects of each session were delivered as guided tasks. In the placebo arm, the allocation of tasks as guided or unguided was determined based on a predefined matching procedure to replicate the distribution of guided and unguided tasks in the intervention arm. The feedback of the online coaches was manualized: Within a special section of the HBI, the coach was able to choose one out of XX pre-build answers for each guided task \[BEARBEITUNG DER ÜBUNGEN UND WIE COACH FEEDBACK GAB GENAUER ERKLÄREN\]. Furthermore, an in-app messaging system allowed the user to communicate in real-time with the online coach as well as the supervision officer. It was ensured that messages and feedback for guided tasks has been provided within 36 hours by the coach. Finally, an online first aid kit was provided for each user and filled with individual skills prepared by the user itself during guided tasks in the intervention arm. In the placebo arm, the first add kit was not individualized but pre-filled with basic hints. Throughout all modules, the speech was friendly, empathetic, simple, and easy to understand (e.g., no technical terms, examples of everyday life) in order to account for the different cognitive functioning level of participants.

Im teilnehmerbereich wurden auf der landing page übersichtlich alle wichtigen Informationen dargeboten (wie man weiter machen kann, ob noch guided tasks bearbeitet werden müssen, ob Fragebögen beantwortet werden müssen, ob neue Nachrichten vorhanden sind). zudem gab es links zu den Avataren, Geldwechsel, in-app messenger, guided-task review board...

Additionally, an in-app alert was shown to the supervision officer about unanswered messages, critical events and time delay of a participant.

#### The \@myTabu intervention

The content of the intervention arm focused exclusively on psychological meaningful risk factors [@mannAssessingRiskSexual2010; @setoEmpiricallybasedDynamicRisk2023]. Already established therapeutic concepts from in-face community-based treatment programs for individuals who committed sexual offenses against children [@brikenPraeventionSexuellenKindesmissbrauchs2017; @wildPreventionSexualChild2020] as well as cognitive-behavioral treatment concepts [see @tbl-sec-outcomes and @frombergerMyTabuAPlaceboControlled2021 for more details] have been adapted for be used online. Both programs have been designed for CSA as well as CSAM offenders. Parts relevant to the meaningful risk factors of both in-face programs have been digitalized and parts on risk factors not supported by empirical evidence have been skipped in order to shorten the HBI. Virtual participants (four male and one female with different offense histories [CSAM exclusive, CSA-exclusive, one released from high security hospital, one from prison and so on.....NOCH GENAU BESCHREIBEN]) accompanied the participant, narrate about their experiences, and make suggestions from the perspective of someone who is also affected (scored by professional actor). All modules within the intervention arm comprised techniques of motivational interviewing [@rollnickMotivationalInterviewingTreatment2015] to enhance or maintain the motivation of the participants. The WBI is designed for female as well as male participants, but due to a lack of knowledge with regard to specific risk factors for female sex offenders at development of the HBI, the content remains identical for women and men. In order to make the HBI suitable for female participants, the used language was adapted and one female virtual participant has been designed and integrated.

Since the treatment programs \@myTabu is based on, are following slightly different theoretical frameworks, the intervention must be defined as an eclectic treatment approach. The intervention is based in cognitive-behavioral treatment techniques, follows the GLM and partly the RNR approach and integrates techniques from DBT and other thir wave psychotherapy.

The placebo arm was developed to ensure the same mode, dose, and amount of support and attention by supporting online coaches as in the intervention arm - but the content of the modules was unrelated to meaningful dynamic risk factors. The content of the placebo condition comprised information on healthy living, e.g., healthy nutrition, physical activities, or healthy sleep. The amount of exercises was the same as in the experimental condition but exercises are specifically designed to not induce any sustainable effect. The entire content of the HBI is available online under an open-source license after publication (LINK will be provided after publication).

During the clinical trial, in summary one male and three female online coaches cared the participants online. All coaches had a master degree in psychology, one coach ein approbierter Psychotherapeut. Regular meetings between online coaches and an experienced supervisor promoting treatment consistency and regular supervision (one meeting per month) took place.  \[MUSS DAS ZU DEN ERGEBNISSEN????\]

### Outcomes

-   State the prespecified primary and secondary outcomes, including the specific measurement variable (eg, systolic blood pressure), analysis metric (eg, change from baseline), method of aggregation (eg, median, proportion), and timepoint for each outcome;

#### Primary outcomes

The study protocol predefined two primary endpoints. The first was the proportion of officially recorded re-offenses, considered the gold standard for evaluating the treatment efficacy of offender rehabilitation programs [@beechCollaborativeOutcomeData2007]. This endpoint will be assessed five years after the last patient out (September 2030). The second primary endpoint, the Index of Desistance (IoD), was intended to measure the relative effectiveness of the intervention arm in reducing dynamic risk factors compared to the placebo arm. Originally, the IoD was conceptualized as a composite measure comprising three self-report instruments developed at the outset of the @myTabu project: the Acute-SR, the Stable-SR, and the Checklist of Behavioral Misconduct (CMC) [@nitscheErfassungAkutUnd2022]. However, the evaluation by @nitscheErfassungAkutUnd2022 revealed that the CMC exhibited low internal consistency (Cronbach’s α = 0.53). To improve psychometric quality, a comprehensive item reduction was undertaken. Based on these findings, and deviating from the Statistical Analysis Plan (SAP), the CMC was excluded from the primary outcome, and only the scales with reduced item sets were retained. Furthermore, we decided to report results for the validated CARES scale instead (see ??? for a detailed analysis of the IoD as defined in the SAP).
Accordingly, the primary outcome is now defined as the Child Sexual Abuse Risk Evaluation Self-Report (CARES) scale, a composite instrument integrating the CARES-A, which assesses acute dynamic risk factors, and the CARES-S, which measures stable dynamic risk factors [@sonjaetzlerDevelopmentInitialValidationsubmitted]. The CARES total score is calculated by summing the CARES-A and CARES-S total scores, producing a range from 0 to 102, with higher scores indicating greater severity of both acute and stable dynamic risk factors. The CARES-A scale evaluates seven acute dynamic risk factors associated with sexual reoffending in individuals convicted of at least one (contact or non-contact) sexual offense against children: (1) Preoccupation with Potential Victims, (2) Hostility, (3) Hypersexuality, (4)  Rejection of Control Measures, (5) Emotional Crisis, (6) Loss of Social Support, and (7) Substance Use. Comprising 21 items, the CARES-A yields scores from 0 to 42; higher scores denote more pronounced acute dynamic risk. Reliability coefficients for the CARES-A range from α = .79 to α = .83. Analyses of social desirability revealed no significant correlations between CARES-A scores and either the Exaggeration of Positive Qualities or Negative Qualities [@sonjaetzlerDevelopmentInitialValidationsubmitted].
The CARES-S scale assesses six stable dynamic predictors of sexual recidivism. It consists of 30 items covering: (1) Problematic Sexual Interests, (2) Problematic Emotion-Regulation, (3) Lack of Problem-Solving Skills, (4) Offense-Supportive Cognitions, and (5) Lack of Social Support. Five of these subscales correspond to empirically supported psychological risk factors for sexual recidivism [@mannAssessingRiskSexual2010; @setoEmpiricallybasedDynamicRisk2023]. The CARES-S total score ranges from 0 to 60; higher scores indicate stronger stable dynamic risk factors. The reduced CARES-S achieved an internal consistency of α = .53. As with the CARES-A, no significant correlations with social desirability measures were found in the evaluation study [@sonjaetzlerDevelopmentInitialValidationsubmitted].Primary outcome data (CARES) were collected at seven measurement time points (see TABLE OF TIME POINTS).

#### Secondary outcomes

Pre–post difference scores of psychometric questionnaires in the treatment arm compared with the placebo arm are defined as secondary endpoints. All secondary endpoints, including their measurement variables, analysis metrics, aggregation methods, and time points, are summarized in [@tbl-sec-outcomes]. Each secondary endpoint corresponds to a questionnaire designed to assess (at least some aspects of) one of the risk factors targeted by the intervention modules. Each questionnaire is administered before (pre) and after (post) the module addressing the respective risk factor. [@apx-desc-sec-endpoints] provides a detailed description of each questionnaire.

<!-- {{< include _includes/tbl_sec_outcomes_riskfactors.qmd >}} -->

#### Assessment of harms

Stopping guidelines have been prospectively defined for the interim analysis. A participant was excluded if the responsible supervision officer or the online coach reports clear evidence for sexual recidivism or concrete preparations for any sexual recidivism. The clinical trial would have been stopped if an interim analysis at 12 months after first patient in (tested on subjects having completed at least two modules of the web-based intervention) demonstrates: (a) a significantly higher risk to re-offend (based on main outcome and number of reported significant events in the experimental condition compared to the placebo condition); (b) a significantly higher proportion of reported significant events (see a) in the experimental condition than in the placebo condition; (c) a significantly increased proportion of high-risk subjects (defined in terms of the main outcome) compared to the proportion at baseline.

Re-offenses during working on the HBI as reported by the community supervisors were derived from the Exclusion Questionnaire (EQ). Furthermore, recidivism or concrete preparations for recidivism as reported in in-app messages or during working on a guided tasks have been measured in order to not oversee any potential risk. The EQ assess the reasons for exclusion in a structured manner and had to be filled in by the supervisor at exclusion of a participant. The EQ asks for XX potential reasons for exclusion, darin enthalten.... IThe EQ allows to specifiy multiple reasons for exclusion of a participant.

::: {.callout-important}
genauere Beschreibung des EQ und dessen Skalen
:::

Potential harms have been accessed by the Mood and Risk Questionnaire (MRQ). The MRQ was developed to assess acute changes with regard to emotional well-being (suicidal ideations, mental crisis) and thoughts associated with potential re-offenses. It consists of ten self-developed items, of which six are asking about thoughts and behaviors associated with potential re-offenses and four asking about the psychological and emotional state of the participant. The MRQ has been assessed before and after each session of the HBI. The MRQ slightly differs between the items in the pre and post measurements: all items of the pre measurement refer explicitly to the time between finishing last post measurement and before starting the new session (time not working on the HBI). The post measurement explicitly asks for the time during working on the session. The MRQ has not been mentioned in the SAP due to a mistake by the PI.

Finally, detoriation of psychological well-being has been assessed with the WHO-5 Well-Being Index [WHO-5; @bechMeasuringDimensionPsychological2004]. The WHO-5 is a self-report questionnaire that measures current mental well-being based on five items  rated on a six-point Likert-scale ranging from 0 (at no time) to 5 (all of the time). The WHO-5 has shown good validity in measuring subjective well-being in clinical studies [@toppWHO5WellbeingIndex2015]. The WHO-5 was administered before an after each session of the WBI. The WHO-5 has not been mentioned in the SAP due to a mistake by the PI.

#### Ancillary outcomes

Without predefined hypotheses, some questionnaires have been administered in an explorative manner.  Since it has been discussed if a therapeutic alliance can be established even with offenders [LIT], it is important to proof if a therapeutic alliance was build during participation. The Working Alliance Inventory-Short Revised [WAI-SR; @horvathDevelopmentWorkingAlliance1986; @horvathDevelopmentValidationWorking1989] measures three dimensions of therapeutic alliance. For the purpose of this study, the original items of the German version [@wilmersDeutschsprachigeVersionWorking2008] were adapted to be suitable for a web-based intervention. The items have to be rated on a five-point Likertscale ranging from 1 (never) to 5 (always). It was adapted to suit to the online-coach as well as the supervision-officer resulting in 16 items. Internal consistency (Cronbach’s α) of the original questionnaire ranges from 0.82 to 0.90 [@wilmersDeutschsprachigeVersionWorking2008]. The WAI-SR was developed in a version asking for bonding with the supervisor as well as a version asking for therapeutic alliance with the online coach. The WAI-SR was assessed only on six timepoints, always after finishing the first session of a module.

In order to assess a possible volunteer-effect, the Questionnaire of Non-Participation (QNP) was developed to assess possible reasons for not taking part in the clinical trial and to assess the baseline characteristics of non-participanmts in order to be able to get a representative baseline for all individuals convicted for CSA or CSAM under community supervision in Germany. Up to now, there exists no official statistic on individuals under community supervision at Germany. The QNP was only administered if a potential participant will not take part in the study but has given informed consent to fill out the QNP.

Finally, the Questionnaire for Acceptance of Technology (ATQ) was administered in order to assess acceptance of technology and its predictors within the framework of this project. Further, the Questionnaire of Subjective Therapy Preconditions [SBV-R; @endresFragebogenSubjektivenBehandlungsvoraussetzungen2010] was used to measures the subscale "pressure of pain" of the multidimensional construct of therapy and treatment preconditions in offenders. These questionnaires were parts of dissertation projects and preliminary data from the intermediate analysis has already been published with regard to the ATQ [@schroderAcceptanceWebBasedIntervention2024; @schroderEngagementWebbasedIntervention2025] or will be published elsewhere.

### Sample size

A rate of 50% of screened participants taking voluntarily part in the clinical trial is assumed. Based on the estimation responsible minsitries, it was expected to see 1,165 subjects eligible for participation during the recruitment period of which 50% (n = 582) have been expected to participate in the study. Taking a dropout of 26.4% (128) into account, it was expected to see n = 428 subjects completing HBI. With n = 214 subjects in both conditions (treatment and placebo) it is possible to detect small effects (d = 0.27) with a power of 80% at a significance level α = 5%.

### Statistical analysis

Data analysis was performed using the software R, version 4.5.0 [@rcoreteamLanguageEnvironmentStatistical2025]. Interim analysis has been done by the data safety monitoring board (DSMB) on April 20, 2022. After receiving permission by the DSMB, partial data from the interim analysis (n = ???; only baseline measures; no data of primary or secondary endpoints) have been already published [@schroderAcceptanceWebBasedIntervention2024; @schroderEngagementWebbasedIntervention2025]. For all analyses on the primary and safety endpoints the intention-to-treat (ITT) population will be used. The ITT population consists of all participants who have completed at least one module but not necessarily answered the questionnaires ate the end of module one.

The primary outcome (CARES total score) was analyzed by means of Gaussian linear model for repeated measures (MMRM) with treatment group, time (six time-points; after each online intervention module), treatment-by-time interaction, and the randomization strata as factors (offense type, type of CS, external treatment in addition to CSaU), baseline measurements (at clearing up) of the outcome and potentially time span from baseline as covariate and the classical IoD as dependent variable. The error terms were assumed to follow a multivariate normal distribution with unstructured covariance. Least squares mean changes from baseline are reported for the treatment groups with 95% confidence interval (CI) as well as the difference between the least squares treatment group means with 95% CI and p-value testing the null hypothesis of no treatment effect. A sensitivity analysis on imputed values complemented the analysis. Imputation has been done using multiple reference based imputation followed by ANCOVA models [@wolbersStandardReferencebasedConditional2022]. Additionally, differences (post - pre) of IoD total score have been compared between the treatment groups using the Brunner-Munzel test for unpaired data [@brunnerNonparametricBehrensFisherProblem2000]. All patients who discontinue from the study are identified and the extent of their participation in the study reported. If discontinuation from study is due to clear evidence for recidivism or concrete preparation for or intention to recidivism (assessed by responsible supervision officer or online coach) the subject receives the maximal value for IoD for the remaining measurements (assuming the worst case of a failed treatment). In all other cases of drop-out, the reason is recorded.

To analyze the treatment effects of each individual module, secondary endpoints have been analyzed using the non-parametric Brunner-Munzel test [@brunnerNonparametricBehrensFisherProblem2000] for paired data comparing the pre- and post-module scores and adjusting the p-values using the Bonferroni-Holm’s method to control the family-wise error rate. The effect of each module on the scores corresponding to the secondary endpoints was exploratory further analyzed by fitting linear models with treatment group and the randomization strata as factors (offense type, type of CS, external treatment in addition to CSaU), pre module scores as covariate and post module scores as dependent variable if appropriate. If necessary, the scores have been transformed before the analysis. If the assumptions of a linear model were not fulfilled either an ordinal regression model was fitted analogously instead or the score was dichotomized in order to fit a logistic regression model analogously. Analyses on the secondary endpoints were carried out on the specific per-protocol (PP) population. The PP population for a specific module consists of all participants who have completed this module.

Proportions of occurrences of re-offences during the clinical trial (as assessed by the EQ) were estimated with 95% confidence intervals for both groups using the beta product confidence procedure for right censored data [@fayPointwiseConfidenceIntervals2013] and differences in the proportions between both groups are estimated with 95% confidence intervals using the beta product confidence procedure for right censored data [@fayCombiningOneSampleConfidence2015]. Kaplan–Meier survival curves were estimated to examine time to first recidivism event as reported by supervision officers. In order to assess the frequency of clinical significant detoriations in psychological well-being, a detoriation of more than 10 points on the WHO-5 score between the beginning and end of a module was defined as a clinical significant detoriation [@toppWHO5WellbeingIndex2015]. Frequencies and percentages of the number of clinically significant detoriations of psychological well-being (WHO-5 score) as well as frequencies and percentages of the scores on the singe-item subscales of the MRQ were provided for each treatment arm by session and differences between arms on each subscale were compared using Fisher’s exact test. Only measures of the MRQ after each session are considered since the MRQ pre questionnaires asked explicitly on the time before the session (see Table XX - XY for results on the MRQ pre-scores).

Ancilliary outcomes have been analyzed in a exporatory manner. In order to analyze the effect of the treatment arm on psychological well-being, the total score of the WHO-5 was analyzed by means of Gaussian linear model for repeated measures (MMRM) with treatment group, time (six time-points; after each online intervention module), treatment-by-time interaction, and the randomization strata as factors (offense type, type of CS, external treatment in addition to CSaU), baseline measurements (at clearing up) of the outcome and potentially time span from baseline as covariate and the classical IoD as dependent variable. The error terms were assumed to follow a multivariate normal distribution with unstructured covariance. Least squares mean changes from baseline are reported for the treatment groups with 95% confidence interval (CI) as well as the difference between the least squares treatment group means with 95% CI and p-value testing the null hypothesis of no treatment effect. The same analysis rationale was applied for the WAI-SR.

### Role of funding source

The work was funded by the German Federal Ministry of Education and Research (Funding number: 01KR1807A). The funder of the study had no role in study design, data collection, data analysis, data interpretation, or writing of the report.